### ISSUE TITLE
Other: i18n support for Simplified Chinese

### ISSUE THREAD

**Issue by Staruin** [BitsOfAByte/KikoGuide#34]
### Preflight Checklist

- [x] I have searched for existing issues and cannot find mine, or existing issues do not fit.

### Issue

I'm going to localize the KikoGuide to Simplified Chinese, but I cant find the project of Simplified Chinese in Crowdin. 
**Maybe you can add a project of Simplified Chinese in Crowdin? Thanks.**

**Comment by Staruin** [comment]
And I glanced the Localizable.json but didn't find the discribe of mechanisms, duty type, mechanisms type. Is forgeting to add them or can't translate?

**Comment by BitsOfAByte** [comment]
Some parts of KikoGuide are not easy to, or cannot be translated due to the way the code is structured. This includes things like duty types, difficulties, mechanics, etc. 

I'm sure a way exists to localize them easily, but it's fairly low priority at the moment as the English part of the plugin has not been completed yet 

I've added Simplified Chinese to the project Crowdin for now
