### ISSUE TITLE
Feature: i18n support

### ISSUE THREAD

**Issue by MKhayle** [BitsOfAByte/KikoGuide#4]
### Preflight Checklist

- [X] I have searched for existing issues and cannot find mine, or existing issues do not fit.

### New or Existing?

New feature

### Summary of your suggestion.

Adding i18n support with, preferably, Crowdin support as it is the one most XIVLauncher translators are used to.

### Why should this be added or changed?

Increased accessibility (although it may be kinda heavy in terms of translations)

**Comment by BitsOfAByte** [comment]
Support should already be in place for the plugin & duties to be localized (https://github.com/BitsOfAByte/KikoGuide/tree/main/src/Resources/Localization) as long the respective language is marked as supported 

As for Crowdin, that's something I plan to take a look into integrating as soon as I can

**Comment by BitsOfAByte** [comment]
Update on this, I believe I have setup/configured Crowdin to sync with GitHub with any changes now. 

I've only decided to add Plugin strings for a while because the duty translations are a little more involved and will require a restructure to the localizations directory.

Crowdin link (https://crowdin.com/project/kikoguide) & guide will be included in the contributing file whenever I finish that up

Let me know if you have any other issues/questions regarding i18n

**Comment by MKhayle** [comment]
Alright, this will do ! Thanks a lot. 
Also, duty translations can indeed be a bigger resource so I understand you'll wait for a better structure to handle it, no worries.
